services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freelancehub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./
      target: development

    command: npm run dev

    ports:
      - "5000:5000"

    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

    env_file:
      - ./.env

    depends_on:
      - db
volumes:
  postgres_data: