#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo "Running linting and prettier on backend..."

(cd server && npm run pre-commit)

echo "Backend's job is done."

echo "Running linting and prettier on frontend..."

(cd app && npm run pre-commit)
echo "Frontends job is done."
